[package]
name = "pb"
version = "0.1.0"
authors = ["shane <shane@digitalsanctum.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
json = "0.12.4"
mustache = "0.9.0"
serde_derive = "1.0.124"
serde = "1.0.124"
serde_json = "1.0.56"
